# Generated by Django 6.0.3 on 2026-04-01 17:22

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=16, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('category', models.CharField(blank=True, max_length=80)),
                ('color', models.CharField(blank=True, max_length=40)),
                ('size', models.CharField(blank=True, max_length=20)),
                ('cost_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('sale_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('quantity', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-quantity', 'name'],
            },
        ),
    ]
